# Generated by Django 5.0.6 on 2026-09-23 06:18

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("country_code", models.CharField(default="+977", max_length=5)),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("seller", "Seller"),
                            ("collector", "Collector"),
                            ("admin", "Admin"),
                        ],
                        default="seller",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ne", "Nepali")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                ("country_code", models.CharField(default="+977", max_length=5)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("seller", "Seller"),
                            ("collector", "Collector"),
                            ("admin", "Admin"),
                        ],
                        default="seller",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("ne", "Nepali")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login / signup"),
                            ("withdraw", "Wallet withdrawal confirmation"),
                        ],
                        default="login",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "accounts_otp_request",
                "indexes": [
                    models.Index(
                        fields=["phone_number", "purpose"],
                        name="accounts_ot_phone_n_0d5a8e_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "created_at"],
                        name="accounts_ot_phone_n_262594_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=10,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("fcm_token", models.TextField(blank=True, null=True)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_device",
            },
        ),
        migrations.AddConstraint(
            model_name="userdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device_id", ""), _negated=True),
                fields=("user", "device_id"),
                name="unique_device_per_user",
            ),
        ),
    ]
