# Generated by Django 5.0.6 on 2026-09-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dropoff", "0002_remove_legacy_models"),
        ("materials", "0001_initial"),
        ("pickups", "0002_remove_legacy_models"),
    ]

    # Drop the old (empty) tables whole, children first. Removing fields one by
    # one first trips over the old (category, name) unique constraint.
    operations = [
        migrations.DeleteModel(name="RateHistory"),
        migrations.DeleteModel(name="Material"),
        migrations.DeleteModel(name="Category"),
    ]
