# Generated by Django 5.0.6 on 2026-09-26 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0002_remove_legacy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name_en", models.CharField(max_length=60)),
                ("name_ne", models.CharField(max_length=60)),
                ("abbr", models.CharField(max_length=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("metal", "Metal"),
                            ("paper_plastic", "Paper & plastic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "materials_material",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(default="Kathmandu", max_length=40)),
                ("price_per_kg", models.PositiveIntegerField()),
                (
                    "effective_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="materials.material",
                    ),
                ),
            ],
            options={
                "db_table": "materials_rate",
                "indexes": [
                    models.Index(
                        fields=["material", "city", "-effective_date"],
                        name="rate_lookup_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="materialrate",
            constraint=models.UniqueConstraint(
                fields=("material", "city", "effective_date"),
                name="unique_rate_per_day",
            ),
        ),
    ]
