# Generated by Django 5.0.6 on 2026-09-26 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0002_remove_legacy_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=30)),
                ("area", models.CharField(max_length=80)),
                ("line", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=60)),
                ("ward", models.PositiveSmallIntegerField()),
                ("landmark", models.CharField(blank=True, max_length=120)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sellers_address",
                "ordering": ["-is_default", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-is_default", "created_at"],
                        name="address_user_idx",
                    )
                ],
            },
        ),
    ]
