# Generated by Django 5.0.6 on 2026-09-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pickups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickupitem",
            name="pickup",
        ),
        migrations.RemoveField(
            model_name="pickupitem",
            name="material",
        ),
        migrations.DeleteModel(
            name="Pickup",
        ),
        migrations.DeleteModel(
            name="PickupItem",
        ),
    ]
