# Generated by Django 5.0.6 on 2026-09-26 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0003_api_v2"),
        ("pickups", "0002_remove_legacy_models"),
        ("sellers", "0003_api_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pickup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ref", models.CharField(max_length=16, unique=True)),
                ("area", models.CharField(max_length=80)),
                ("address_line", models.CharField(max_length=255)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "delivery_option",
                    models.CharField(
                        choices=[
                            ("self_dropoff", "Self drop-off"),
                            ("collector_pickup", "Collector pickup"),
                            ("truck_helper", "Truck + helper"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("slot_start", models.DateTimeField(blank=True, null=True)),
                ("slot_end", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("matched", "Matched"),
                            ("on_the_way", "On the way"),
                            ("arrived", "Arrived"),
                            ("weighing", "Weighing"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "approx_weight_kg",
                    models.DecimalField(decimal_places=1, max_digits=8),
                ),
                ("estimated_total", models.PositiveIntegerField()),
                ("delivery_fee", models.PositiveIntegerField(default=0)),
                ("estimated_payout", models.PositiveIntegerField()),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("collector_earning", models.PositiveIntegerField(default=0)),
                ("final_total", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "final_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                ("payout_method", models.CharField(blank=True, max_length=10)),
                (
                    "settlement_status",
                    models.CharField(
                        blank=True,
                        choices=[("paid", "Paid"), ("held", "Held")],
                        max_length=10,
                    ),
                ),
                ("held_payout", models.PositiveIntegerField(blank=True, null=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("on_the_way_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("weighing_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("disputed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("changed_mind", "Changed mind"),
                            ("sold_elsewhere", "Sold elsewhere"),
                            ("wrong_time", "Wrong time"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cancel_note", models.CharField(blank=True, max_length=200)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sellers.address",
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickups_as_collector",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickups_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pickups_pickup",
            },
        ),
        migrations.CreateModel(
            name="PickupRefCounter",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("last_value", models.PositiveIntegerField(default=2400)),
            ],
            options={
                "db_table": "pickups_ref_counter",
            },
        ),
        migrations.CreateModel(
            name="WeighSheet",
            fields=[
                (
                    "pickup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="weigh_sheet",
                        serialize=False,
                        to="pickups.pickup",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("disputed", "Disputed"),
                        ],
                        default="live",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pickups_weigh_sheet",
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("weight_disagreement", "Weight disagreement"),
                            ("missed_pickup", "Missed pickup"),
                            ("payment", "Payment"),
                            ("behaviour", "Behaviour"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                ("adjusted_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="pickups.pickup",
                    ),
                ),
            ],
            options={
                "db_table": "pickups_dispute",
            },
        ),
        migrations.CreateModel(
            name="PickupDecline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("too_far", "Too far"),
                            ("wrong_time", "Wrong time"),
                            ("not_worth_it", "Not worth it"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declines",
                        to="pickups.pickup",
                    ),
                ),
            ],
            options={
                "db_table": "pickups_decline",
            },
        ),
        migrations.CreateModel(
            name="PickupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approx_kg", models.DecimalField(decimal_places=1, max_digits=7)),
                ("price_per_kg", models.PositiveIntegerField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="materials.material",
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pickups.pickup",
                    ),
                ),
            ],
            options={
                "db_table": "pickups_item",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PickupRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveSmallIntegerField()),
                ("comment", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="pickups.pickup",
                    ),
                ),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pickups_rating",
            },
        ),
        migrations.CreateModel(
            name="WeighLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_per_kg", models.PositiveIntegerField()),
                ("kg", models.DecimalField(decimal_places=1, max_digits=7)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="materials.material",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pickups.weighsheet",
                    ),
                ),
            ],
            options={
                "db_table": "pickups_weigh_line",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="WeighFlag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("weight_too_high", "Weight too high"),
                            ("wrong_material_or_rate", "Wrong material or rate"),
                            ("something_else", "Something else"),
                        ],
                        max_length=30,
                    ),
                ),
                ("expected", models.CharField(blank=True, max_length=40)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags",
                        to="pickups.dispute",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="materials.material",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="pickups.weighsheet",
                    ),
                ),
            ],
            options={
                "db_table": "pickups_weigh_flag",
            },
        ),
        migrations.AddIndex(
            model_name="pickup",
            index=models.Index(
                fields=["seller", "status", "slot_start"], name="pickup_seller_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickup",
            index=models.Index(
                fields=["collector", "status"], name="pickup_collector_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickup",
            index=models.Index(
                fields=["status", "slot_end"], name="pickup_status_slot_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickup",
            index=models.Index(
                fields=["status", "lat", "lng"], name="pickup_open_geo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickup",
            index=models.Index(
                fields=["settlement_status", "seller"], name="pickup_settlement_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["pickup", "status"], name="dispute_pickup_idx"),
        ),
        migrations.AddConstraint(
            model_name="pickupdecline",
            constraint=models.UniqueConstraint(
                fields=("pickup", "collector"), name="unique_decline"
            ),
        ),
        migrations.AddIndex(
            model_name="pickuprating",
            index=models.Index(fields=["ratee"], name="rating_ratee_idx"),
        ),
        migrations.AddConstraint(
            model_name="pickuprating",
            constraint=models.UniqueConstraint(
                fields=("pickup", "rater"), name="unique_rating_per_side"
            ),
        ),
        migrations.AddConstraint(
            model_name="weighline",
            constraint=models.UniqueConstraint(
                fields=("sheet", "material"), name="unique_line_per_material"
            ),
        ),
        migrations.AddIndex(
            model_name="weighflag",
            index=models.Index(fields=["sheet", "status"], name="flag_sheet_idx"),
        ),
    ]
