# Generated by Django 5.0.6 on 2026-09-26 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dropoff", "0002_remove_legacy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropoffCenter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=255)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                ("accepts", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dropoff_center",
                "indexes": [
                    models.Index(
                        fields=["is_active", "lat", "lng"], name="dropoff_geo_idx"
                    )
                ],
            },
        ),
    ]
