# Generated by Django 5.0.6 on 2026-09-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
