# Generated by Django 5.0.6 on 2026-09-26 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_api_v2"),
        ("pickups", "0003_api_v2"),
        ("wallet", "0002_remove_legacy_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wallet",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallet_wallet",
            },
        ),
        migrations.CreateModel(
            name="PayoutMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("bank", "Bank")], default="bank", max_length=10
                    ),
                ),
                ("bank_code", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=80)),
                ("account_name", models.CharField(max_length=120)),
                ("account_number", models.CharField(max_length=30)),
                ("is_default", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_payout_method",
                "ordering": ["-is_default", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("withdrawal", "Withdrawal"),
                            ("dropoff", "Drop-off"),
                            ("job_earning", "Job earning"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=10,
                    ),
                ),
                ("affects_balance", models.BooleanField(default=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payout_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="wallet.payoutmethod",
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="pickups.pickup",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transaction",
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"], name="txn_wallet_recent_idx"
                    ),
                    models.Index(
                        fields=["wallet", "type", "status", "created_at"],
                        name="txn_wallet_type_idx",
                    ),
                ],
            },
        ),
    ]
