# Generated by Django 5.0.6 on 2026-09-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
