# Generated by Django 5.0.6 on 2026-09-26 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_api_v2"),
        ("notifications", "0002_remove_legacy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_preference",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pickup_updates", models.BooleanField(default=True)),
                ("rate_alerts_enabled", models.BooleanField(default=False)),
                ("rate_alert_material_ids", models.JSONField(blank=True, default=list)),
                ("promotions", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notifications_preference",
            },
        ),
    ]
